### ISSUE TITLE
WebApp with type Web - SAML + Provisioning (template "AWS")

### ISSUE THREAD

**Issue by rjudin** [marcozj/terraform-provider-centrifyvault#4]
We are configuring Federated access over Centrify to AWS Accounts as Web Access with type `Web - SAML + Provisioning`

Example desired state:
```typescript
locals {
  aws_account = {
    one = {
      alias = "xxx-dev-account1"
      id    = "12325375486"
    }
    two = {
      alias = "xxx-dev-account2"
      id    = "12343375483"
    }
  }
}

resource "centrifyvault_webapp" "one" {
  description = "AWS :: SAML2 :: ${local.aws_account.one.alias}"

  type       = "Web - SAML + Provisioning" # template AWS
  account_id = local.aws_account.one.id
  name       = local.aws_account.one.alias

  saml_response {
    attribute {
      name  = "https://aws.amazon.com/SAML/Attributes/SessionDuration"
      value = "900"
    }
    custom_logic = <<-EOF
    setVersion('2');
    setIssuer(Issuer);
    setSubjectName(LoginUser.Email);
    ...
    EOF
  }
  permissions {...}
  account_mapping {
    directory_service_field = "mail"
    # script = <<-EOF ... EOF # optional
  }

  workflow {} # desired to have

  sets = [] # desired to have

}

output "idp_metadata_xml_file" {
  description = "Metadata XML file content that required to create AWS Identity Provider"
  value       = centrifyvault_webapp.one.metadata_xml_file
}

output "idp_metadata_xml_url" {
  description = "Metadata XML URL that needs to be downloaded before creating AWS Identity Provider"
  value       = centrifyvault_webapp.one.metadata_xml_url
}

```

Could you please make it available in terraform provider?

![image](https://user-images.githubusercontent.com/31796644/112615217-7ea97880-8e22-11eb-9bac-233c9eadad4f.png)

![image](https://user-images.githubusercontent.com/31796644/112615426-c4664100-8e22-11eb-91c5-13e451aa9750.png)

![image](https://user-images.githubusercontent.com/31796644/112615542-e364d300-8e22-11eb-8014-5411c711af90.png)

![image](https://user-images.githubusercontent.com/31796644/112615615-f7a8d000-8e22-11eb-8bac-f780b86a04f1.png)

![image](https://user-images.githubusercontent.com/31796644/112615755-2fb01300-8e23-11eb-8677-9568b94d07af.png)

**Comment by marcozj** [comment]
This is added in release v0.1.3
