### ISSUE TITLE
Allow terraform import

### ISSUE THREAD

**Issue by rjudin** [marcozj/terraform-provider-centrifyvault#7]
We noticed that some existing Centrify resources not possible to import into tfstate

We can get `id` of the resource by fetching data

```
data "centrifyvault_xxx_xxx" "my_resource" {
  name = "My App - Admin"
}

output "my_resource" {
  value = data.centrifyvault_xxx_xxx.my_resource.id
}

```

Which will be used during import (with prepared new resources in code `centrifyvault_xxx_xxx.my_resource`)
```
terraform import centrifyvault_xxx_xxx.my_resource XXX-XXXX-XXXX-XXX 
```
But last step failed in the same way `Error: Invalid provider configuration` -> `provider "centrifyvault"`
> The configuration for provider["registry.terraform.io/marcozj/centrifyvault"]
depends on values that cannot be determined until apply.

**Please allow `terraform import` based on resource_id** for all possible Centrify resources

Tested on resource types:
- centrifyvault_webapp_generic
- centrifyvault_role

**Comment by marcozj** [comment]
resource import will be enabled in next release

**Comment by marcozj** [comment]
v0.1.5 released
